### ISSUE TITLE
NOX theme Layer progess wrong screen position and icon missing

### ISSUE THREAD

**Issue by ipa64** [UnchartedBull/OctoDash#1749]
Hi,
In this case pictures are better than words.

It should be
https://i84.servimg.com/u/f84/20/23/21/77/captur13.png

I get this
https://i84.servimg.com/u/f84/20/23/21/77/img_2810.jpg

Thank you

**Comment by ipa64** [comment]
Tested with theGarbz/Focus same behavior

**Comment by ipa64** [comment]
until v2.1.1 app was layer-progress
from v2.1.2 app is height-progress

**Comment by UnchartedBull** [comment]
Please add the requested information in the issue template. Otherwise no one can help you.

**Comment by pciavald** [comment]
I'm getting the same issue, NOX theme maintainer knows about it (I can't remember which issue it was in) and is already fixing it. @ipa64 you can fix it yourself before by fiddling with the custom css. Something like this
```css
.height-indication {
  width: auto !important;
  position: fixed !important;
  top: 52vh !important;
  left: 59vw !important;
}
```
